cloudfront_purger.settings:
  type: config_object
  label: 'CloudFront Purger Settings'
  mapping:
    distribution_id:
      type: string
      label: 'CloudFront Distribution ID'
    aws_key:
      type: string
      label: 'AWS Key'
    aws_secret:
      type: string
      label: 'AWS Secret'
